### ISSUE TITLE
Readme structure doesn't showcase ES6 support as well as it should

### ISSUE THREAD

**Issue by jnhuynh** [yapplabs/ember-strong-attrs#13]
Pointed out by @elwayman02, the README puts ES6 support info at the very bottom and the caveats section stresses ES7 requirements too much. This prevents adoption by apps that only support ES6. We should restructure the README to emphasize ES6 support more.

**Comment by elwayman02** [comment]
:+1: I was actually considering using Ember-Enforcer over Ember-Strong-Attrs specifically because I didn't want to build addons/components that forced all consuming apps to enable the experimental ES7 syntax.

**Comment by lukemelia** [comment]
Good point!

**Comment by lukemelia** [comment]
Fixed by #14
